name: GitHub Actions Demo
run-name: ${{ github.actor }} start building ðŸ‘·â€â™‚ï¸ðŸ‘·â€â™€ï¸
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    # steps:
    #   - uses: actions/checkout@v3
    #   - name: Use Node.js
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: "16.x"
    #   - name: Install dependencies
    #     run: sh buildAll.sh
    #   #
    #   - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
    #   - run: pwd
    #   - run: ls -la
    #   - run: sh makeSync.sh
    #   - run: |
    #       date > generated.txt
    #       git config user.name github-actions
    #       git config user.email github-actions@github.com
    #       git add .
    #       git commit -m "generated"
    #       git push
